Amélioration de /school et ajout de /gen
prepas-mp2i/mp2i-discord-bot pull request #11
Opened 2024-09-20 17:35 UTC by Triw-12

Ajout d'un paramètre type dans /school : on peut maintenant s'associer avec une école d'ingénieur.
Ajout de la commande /gen : possiblité de choisir l'année de son arrivée en sup
L'école d'ingé et la génération sont affichés dans /profile
On peut afficher les personnes appartenant à une certaine école avec /members

2024-09-20 22:43 UTC, Triw-12 commented
Ajouts de commandes permettant de mettre les lycées/écoles sur la BDD et de pouvoir en ajouter/supprimer

2024-09-21 08:40 UTC, Alessevan requested changes
Une ou deux modifications à faire, si t'as testé le reste c'est OK.

2024-09-21 08:40 UTC, Alessevan commented on mp2i/models.py
> +    name: str = Column(String(50), primary_key=True)
Le nom d'un lycée ne peut pas être une clé primaire car il peut (pas souvent certes) changer. Il faudrait mieux mettre un id.

2024-09-21 08:40 UTC, Alessevan commented on mp2i/models.py
> +    name: str = Column(String(50), primary_key=True)
C'est d'autant plus vrai pour les écoles d'ingénieurs comme Phelma ou plus récemment l'ENSMAC.

2024-09-21 08:40 UTC, Alessevan commented on mp2i/models.py
> +    engineering_school: str = Column(String(50), ForeignKey("engineering_school.name", ondelete="SET NULL"), nullable=True, default=None)
Voir remarques ci-dessus.

2024-09-21 08:40 UTC, Alessevan commented on mp2i/static/text/ecole_inge.txt
Attention, il y a un mélanges d'écoles avec leur ville et d'autres non. Il faudrait donc soit `ENSIBS => ENSIBS Vannes / ENSIBS Lorient`, ou bien `ENSEIRB Bordeaux => ENSEIRB`|

2024-09-21 10:00 UTC, Triw-12 commented
En effet, j'avais fait avec l'id mais l'autoincrémentation ne fonctionnait pas donc je l'avais juste enlevé mais je vais essayer de le modifier ce soir

2024-09-21 21:00 UTC, Alessevan commented on mp2i/cogs/school.py
> +        self.engineering_schools = [x.name for x in engineering_school_list]
ça me paraît bizarre de faire uniquement ça et non des jointures. C'est totomatique ?
Sinon, dis-moi si t'as testé et je valide si c'est le cas.

2024-09-21 21:07 UTC, Triw-12 commented on mp2i/static/text/ecole_inge.txt
Alors ça me paraît pas incohérent parce que ENSIBS a deux campus mais c'est une même formation... 
Donc ce que je vois c'est que c'est école ville sauf si il y a ambiguité sur la ville (dans ce cas on met rien)
Mais je vais rajouter une commande qui permet de modifier le nom d'une école si les règles de nommage changent

2024-09-21 21:08 UTC, Triw-12 commented on mp2i/cogs/school.py
> +        self.engineering_schools = [x.name for x in engineering_school_list]
ça te paraît bizarre de faire deux tables ? Euhh c'est pas aberrant de faire une seule table en effet, je vais mofidier ça

2024-09-21 21:10 UTC, Alessevan commented on mp2i/static/text/ecole_inge.txt
Ok, je trouvais ça mieux (ou plus logique) de faire l'inverse, ne pas mettre la ville s'il n'y a aucune ambiguïté et la mettre dans l'autre cas.

2024-09-21 21:12 UTC, Alessevan commented on mp2i/cogs/school.py
> +        self.engineering_schools = [x.name for x in engineering_school_list]
Non c'était de faire des tableaux des noms, mais je comprends pas trop comment ça fonctionne l'ORM utilisé. Et tu as bien deux tables là, non (Cpge et EngineeringSchool) ?

2024-09-21 22:06 UTC, Triw-12 commented on mp2i/cogs/school.py
> +        self.engineering_schools = [x.name for x in engineering_school_list]
C'est juste plus simple pour moi de le faire comme ça et je n'ai pas trouvé de quoi le faire directement en une requête dans la doc

2024-09-21 22:08 UTC, Triw-12 commented on mp2i/models.py
> +    engineering_school: str = Column(String(50), ForeignKey("engineering_school.name", ondelete="SET NULL"), nullable=True, default=None)
Alors je n'ai pas lié les tables entre eux pour l'instant avec l'id parce que c'est un peu complexe en terme de requete et que ça marche très bien même si ce n'est pas idéal, en particulier lorsque que on update le nom.
J'essaierai de le faire dans les prochains jours...

2024-09-21 22:13 UTC, Alessevan commented on mp2i/cogs/school.py
> +        self.engineering_schools = [x.name for x in engineering_school_list]
Ah non mais deux tables c'était bien haha, j'avais mal lu. Voire t'aurais pu faire trois tables avec un peu d'héritage, mais c'est pas nécessaire.

2024-09-21 23:37 UTC, Triw-12 commented on mp2i/models.py
> +    engineering_school: str = Column(String(50), ForeignKey("engineering_school.name", ondelete="SET NULL"), nullable=True, default=None)
Finalement j'ai réussi (non sans complication) à le faire maintenant

2024-09-21 23:41 UTC, Triw-12 commented
Normalement tout est ok et testé

2024-09-22 00:01 UTC, Triw-12 commented on mp2i/static/text/ecole_inge.txt
Oui je comprends... C'est pas moi qui ai fait la liste j'avoue mais ça me paraît clair comme ça donc au pire on changera plus tard (avec la nouvelle commande update_school ou avec une commande que je créerai si nécessaire)

2024-09-22 06:05 UTC, Alessevan reviewed
Juste ça et ce sera bon pour moi.

2024-09-22 06:05 UTC, Alessevan commented on mp2i/cogs/school.py
> +                if any(r.name == "Ex MPI" for r in ctx.author.roles):
Pas forcément certains de l'intérêt de réserver aux Ex-MPI, mais le réserver à toues les Integrés.
D'ailleurs pourquoi utiliser le nom du rôle et non l'identifiant ?

2024-09-22 10:29 UTC, Triw-12 commented on mp2i/cogs/school.py
> +                if any(r.name == "Ex MPI" for r in ctx.author.roles):
Alors, le problème c'est que pour l'instant les noms d'écoles d'ingé sont uniquement ceux accessibles à la fin d'une MPI... Et le but d'ajouter des écoles d'ingé c'est surtout lorsqu'il aura des référents pour les écoles d'ingé et il y en aura uniquement pour les écoles qui sont après une MPI donc ce sera des Ex MPI...
Et si on accepte tous les Intégrés, suvant cette logique, on devrait aussi accepter à tous les Infiltrés de pouvoir choisir son lycée s'ils sont en prépa, et je trouve que ça pert un peu l'idée d'un discord pour les étudiants en MP2I/MPI.
Après c'est que mon avis, je vais quand même demander aux admins ce qu'ils en pensent !

2024-09-22 10:34 UTC, Alessevan commented on mp2i/cogs/school.py
> +                if any(r.name == "Ex MPI" for r in ctx.author.roles):
La réponse me convient.

2024-09-22 10:34 UTC, Alessevan approved these changes
LGTM.

2024-09-22 10:36 UTC, merged