Amélioration des suggestions communautaires
prepas-mp2i/mp2i-discord-bot pull request #8
Opened 2024-05-17 08:09 UTC by AntoninLoubiere

Fiabilisation du bot, à la place de seulement vérifier `pins.count == self.MINIMUM_PINS`, on vérifie que `pins.count >= self.MINIMUM_PINS` de sorte à quand même envoyer le message si on loupe l'évènement de la 5ème réaction. Le bot réagit au message ensuite pour ne pas le renvoyer.

2024-05-17 08:11 UTC, Triw-12 approved these changes
LGTM

2024-05-19 23:58 UTC, ajayat requested changes

2024-05-19 23:58 UTC, ajayat commented on mp2i/cogs/suggestions.py
> +        if pins is None or pins.count < self.MINIMUM_PINS:
Le problème c'est qu'une fois dépassé MINIMUM_PINS,
À chaque fois qu'un utilisateur autre que le bot réagit au message, le msg va être à nouveau signalé par le bot ?

2024-05-20 07:33 UTC, Triw-12 commented on mp2i/cogs/suggestions.py
> +        if pins is None or pins.count < self.MINIMUM_PINS:
C'est le rôle du filtre me=False, qui va faire en sorte de filtrer les réactions auxquels le bot n'a pas répondu, donc comme la première fois que le bot le voit, il va ajouter sa réaction, toutes les autres fois, le filtre va renvoyer None, donc directement renvoyer rien et ne pas signaler une nouvelle fois le message

2024-05-20 08:28 UTC, ajayat commented on mp2i/cogs/suggestions.py
> +        if pins is None or pins.count < self.MINIMUM_PINS:
Oui en effet, j'ai lu trop vite, et c'est bien un AND de tous les attrs avec get, donc c'est bon.
Autant pour moi (il était tard mdrr)

2024-05-20 08:31 UTC, merged