Ajout de la possibilité de choisir son lycée
prepas-mp2i/mp2i-discord-bot pull request #9
Opened 2024-07-20 14:24 UTC by Triw-12

Modification de la base de donnée : 
- Ajout d'un attribut lycee pour les membres du discord
Ajout et modifications des commandes : 
- `ajout_lycee` : associe un lycée qui possède une MP2I avec celui qui utilise la commande
- 'profile' : affiche le lycee qui est associé

N'ayant pas de serveur de test, **les modifications n'ont pas été testés....**

Futures améliorations (mais il est préférable de tester si ça marche avant de rajouter des améliorations):
- [ ] Modification de la commande `referents` :  affichage du lycée associé plutôt que ce qui est après le @
- [ ] Limitation de l'utilisation de la commande 'ajout_lycee' uniquement aux MP2I/MPI/ex-MPI
- [ ] Ajout d'une commande `modif_lycee` accessible uniquement pour les administrateurs permettant de changer le lycée d'autres personnes
- [ ] Modification de `ajout_lycee` pour permettre de retirer l'association avec un lycée
- [ ] Ajout de la commande `lycees` : pour chaque lycée, affichage du nombre de personnes s'étant associé avec lui

2024-07-20 14:48 UTC, Alessevan approved these changes
Pour ma part, je serais plus partisan d'avoir les lycées dans une table plutôt que dans un fichier texte. Et dans le cas d'un fichier, le lire une fois au début et stocker le nom des lycées dans une liste, au lieu de le lire à chaque fois que la liste des lycées et nécessaire.

Edit : j'avais pas lu le message en gras 😂

2024-07-20 14:48 UTC, Alessevan commented on mp2i/cogs/lycee.py
> +    async def choix_lycee(self, interaction: discord.Interaction, lycee: str):
Juste modifier le nom de la fonction pour avoir quelque chose de plus anglois type `choose_lycee` afin de garder une cohérence avec le nom des autres fonctions.

2024-07-21 11:42 UTC, Triw-12 commented
Ne fonctionne pas encore

2024-07-21 15:59 UTC, Triw-12 commented
Maintenant ça fonctionne, on peut passer aux améliorations

2024-07-21 23:48 UTC, ajayat commented
Super travail,
Quelques petites modifications sur lesquelles on a discuté :
- Renommer `lycee` en school, pour que ça colle mieux avec l'anglais et que ce soit surtout plus générique (dans le cas d'une adaptation future avec les écoles d'ingé)
- Déplacer la commande `referents` de `commands.py` vers `school.py`
- Refactoriser le début de la fonction `schools` en utilisant Counter du module `collections`:
```py
school_members = map(lambda m: MemberWrapper(m).school,  ctx.guild.members)
school_count = Counter(school_members)

for school, c in school_count.items():
    if school == "Aucun":
        continue
    ...
```
- Faire une fonction `is_moderator` dans `utils/checks.py` pour remplacer les décorateurs `@has_permissions(manage_messages=True)` par `check(is_moderator)`
Je me chargerai de rajouter les ID des rôles manquants dans `bot-config.yaml`, de cette façon tu peux le récupérer avec 
```py
role = GuildWrapper(ctx.guild).get_role_by_qualifier("Modérateur")
# role.id
```
- Petite note à moi même : fix `database_name = engine.URL.database`

2024-07-21 23:52 UTC, ajayat requested changes
Super travail,
Quelques petites modifications sur lesquelles on a discuté :
- Renommer `lycee` en school, pour que ça colle mieux avec l'anglais et que ce soit surtout plus générique (dans le cas d'une adaptation future avec les écoles d'ingé)
- Déplacer la commande `referents` de `commands.py` vers `school.py`
- Refactoriser le début de la fonction `schools` en utilisant Counter du module `collections`:
```py
school_members = map(lambda m: MemberWrapper(m).school,  ctx.guild.members)
school_count = Counter(school_members)

for school, c in school_count.items():
    if school == "Aucun":
        continue
    ...
```
- Faire une fonction `is_moderator` dans `utils/checks.py` pour remplacer les décorateurs `@has_permissions(manage_messages=True)` par `check(is_moderator)`
Je me chargerai de rajouter les ID des rôles manquants dans `bot-config.yaml`, de cette façon tu peux le récupérer avec 
```py
role = GuildWrapper(ctx.guild).get_role_by_qualifier("Modérateur")
# role.id
```
- Petite note à moi même : fix `database_name = engine.URL.database`

2024-07-22 16:25 UTC, ajayat approved these changes

2024-07-22 16:26 UTC, merged